
import { NAME } from './constants';

export const IDLE = `${NAME}/IDLE`;

export const LOADING_GET_DETAIL = `${NAME}/LOADING_GET_DETAIL`;
export const GET_DETAIL_DONE = `${NAME}/GET_DETAIL_DONE`;

export const LOADING_GET_LIST = `${NAME}/LOADING_GET_LIST`;
export const GET_LIST_DONE = `${NAME}/GET_LIST_DONE`;

export const LOADING_FILTER = `${NAME}/LOADING_FILTER`;
export const LOADING_FILTER_NEXT = `${NAME}/LOADING_FILTER_NEXT`;
export const FILTER_DONE = `${NAME}/FILTER_DONE`;

export const LOADING_SEARCH = `${NAME}/LOADING_SEARCH`;
export const SEARCH_DONE = `${NAME}/SEARCH_DONE`;

export const LOADING_SET_ROUTES = `${NAME}/LOADING_SET_ROUTES`;
export const SET_ROUTES_DONE = `${NAME}/SET_ROUTES_DONE`;

export const LOADING_ROUTES_BEFORE = `${NAME}/LOADING_ROUTES_BEFORE`;
export const ROUTES_BEFORE_DONE = `${NAME}/ROUTES_BEFORE_DONE`;

export const LOADING_ROUTES_AFTER = `${NAME}/LOADING_ROUTES_AFTER`;
export const ROUTES_AFTER_DONE = `${NAME}/ROUTES_AFTER_DONE`;


